### ISSUE TITLE
table of contents with hyperlinks

### ISSUE THREAD

**Issue by AndreiKingsley** [yeputons/spring-2019-paradigms-tasks#101]
В больших README было бы классно сделать "содержание" как в википедии с гиперссылка на части задания(задание 1, задание 2,  формат и такого типа)

**Comment by yeputons** [comment]
Добавили в [task09](https://github.com/yeputons/spring-2019-paradigms-tasks/tree/master/task09) и [task10](https://github.com/yeputons/spring-2019-paradigms-tasks/tree/master/task10), оно?

**Comment by AndreiKingsley** [comment]
Да, класс
