### ISSUE TITLE
rust tutorial

### ISSUE THREAD

**Issue by AndreiKingsley** [yeputons/spring-2019-paradigms-tasks#107]
Можно выложить небольшой туториал по расту, карго(что качать, как юзать)?

**Comment by edgarzhavoronkov** [comment]
Здравствуйте,

Мы читали лекции по этой книге -- [Rust By Example](https://doc.rust-lang.org/rust-by-example/index.html)
Хорошая вводная видеолекция от Computer Science Center -- [Введение в язык программирования Rust](https://www.youtube.com/watch?v=TiCSWNpeR9Q)

**Comment by AndreiKingsley** [comment]
Спасибо

**Comment by yeputons** [comment]
@AndreiKingsley добавил ссылки на страницу в BSSEWiki:
https://bsse.compscicenter.ru/wiki/index.php?title=%D0%9F%D0%B0%D1%80%D0%B0%D0%B4%D0%B8%D0%B3%D0%BC%D1%8B_1MIT_%D0%B2%D0%B5%D1%81%D0%BD%D0%B0_2019#Rust
