### ISSUE TITLE
Task09: memory leak in queue

### ISSUE THREAD

**Issue by RemmargorP** [yeputons/spring-2019-paradigms-tasks#144]
@yeputons, деструктор в queue не очень похож на деструктор.

**Comment by RemmargorP** [comment]
Хммм, у меня это фиксит still reachable: 72,704 bytes in 1 blocks у valgrind, но на travis всё равно течет >_<

**Comment by RemmargorP** [comment]
Ладно, внезапно оказалось, что до этого ничего не текло, но почему travis упорно показывает, что что-то утекает?

**Comment by yeputons** [comment]
Спасибо за репорт и pull request!

С утечками вообще [сложно](http://valgrind.org/docs/manual/mc-manual.html#mc-manual.leaks). Как я понял, Valgrind умеет показывать четыре вида:

1. Still reachable — на момент выхода из программы был какой-то блок памяти, который не освободили, но на него всё ещё есть указатели. То есть программа могла бы освободить память, но не сделала этого. Это вполне себе случается со стандартной библиотекой (например, какой-нибудь статический буфер для ввода-вывода), см. [тут](https://stackoverflow.com/a/30403709/767632) и [тут](http://valgrind.org/docs/manual/faq.html#faq.reports). Ещё это может произойти, если стандартная библиотека не отдала немедленно системе память, а придержала её себе, чтобы сэкономить время на следующей аллокации. Так что это обычно за ошибку не считается, добавлю в задание. У вас как раз такой случай и конкретная цифра в 72704 как раз гуглится на stackoverflow.
2. Definitely lost — блок есть, но на него нет вообще никаких указателей. Утечка памяти, ошибка, [пример](https://travis-ci.org/yeputons/spring-2019-paradigms-tasks/builds/524355057).
3. Indirectly lost — блок есть, на его есть указатели. но они сами лежат в блоках, на которые нет указателей (т.е. они definitely lost). Тоже утечка памяти. Как отдельная ошибка, впрочем, не репортится (см. опцию ` --errors-for-leak-kinds`), потому что на самом деле проблема в утечке "родительского" блока. [Пример](https://travis-ci.org/yeputons/spring-2019-paradigms-tasks/builds/524368430).
4. Possibly lost — блок есть, указателя на начало блока нет, но есть указатель на середину блока. Например, так может делать `std::string`, судя по руководству Valgrind. Поэтому possibly, а не definitely. Тоже является ошибкой по умолчанию. [Пример](https://travis-ci.org/yeputons/spring-2019-paradigms-tasks/builds/524370986)

Деструктор в `queue` действительно не уничтожает загруженные в очередь данные, а просто убеждается, что очередь пуста. Причина описана в `queue.h`: `queue_pop` удаляет только узлы в очередь, но не сами данные, которые там лежат. То есть ваш деструктор как раз приведёт к потенциальным утечкам памяти. Упражнение: убедитесь в этом :)

Очередь принципиально не может удалить данные, которые в неё загрузили: она не является их владельцем и не знает, как их надо удалять. Вдруг там не память из кучи, а указатель на локальную переменную? Тогда удалять вообще нельзя. А вдруг там структура с указателями и надо по ней пробежаться и рекурсивно удалить подструктуры? Тогда надо угадывать, где там указатели.

Таким образом, если старая реализация деструктора корректно завершилась (не упала по `assert`), то утечек памяти не должно быть.

Если осталось что-то непонятное или любые вопросы — смело переоткрывайте этот issue.
