### ISSUE TITLE
Опечатка?

### ISSUE THREAD

**Issue by Peltorator** [yeputons/spring-2019-paradigms-tasks#176]
https://github.com/yeputons/spring-2019-paradigms-tasks/blob/163b28d637f0efb3dc2605b6aa881d71d8115ad9/task10/src/Robots.hs#L104

Функция точно должна называть так?

**Comment by yeputons** [comment]
Мне кажется, баг, в следующей итерации домашки поправим. Сейчас уже не будем, чтобы не ронять тесты и не плодить конфликты.

Спасибо!
