### ISSUE TITLE
Task06: Update Python to 3.6+

### ISSUE THREAD

**Issue by RemmargorP** [yeputons/spring-2019-paradigms-tasks#39]
Мое решение по Task06 использует способ f-string форматирования, который был добавлен в Python 3.6. Можно ли обновить Python, чтобы pycodestyle в CI не ругался?

**Comment by yeputons** [comment]
@RemmargorP Обновили до Python 3.7 в 6a97929b195149fe08cd7af103ba8951bfb8ff2f . Чтобы заработало в ваших pull requests, надо включить этот коммит в ваши ветки (например, сделав `rebase`).

Если не поможет — переоткройте issue, будем разбираться.
