### ISSUE TITLE
task06: README typos

### ISSUE THREAD

**Issue by Peltorator** [yeputons/spring-2019-paradigms-tasks#93]
@yeputons 
Задача 2: Подробнее: "кроме заканчивающихся на }, нужно ВЫВОДИТ символ ;"
Задача 2: BinaryOperation: "mul = BinaryOperation(Number(0), `*`, add)". Не 0, а 1 должно быть. И кавычки не такие, как в остальных кодах.
Задача 2: UnaryOperation: "pretty_print(Operation('-', Number(42)))`". Лишняя кавычка в конце. И не Operation, а UnaryOperation.

**Comment by yeputons** [comment]
@Peltorator спасибо! Первую поправил (82842328e9d1e7dd1b104280e9b8214184a3160e), вторая вроде уже была поправлена, третью тоже поправил (cc18abb).

Если что-то не поправлено — переоткрывайте issue.

**Comment by Peltorator** [comment]
@yeputons 
А, я просто в своем репозитории смотрел)
